Asm1670-Code asm/Controllers/AuthorController.cs
using Asm1670.Data;
using Asm1670.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace Asm1670.Controllers
{
    public class AuthorController : Controller
    {
        private ApplicationDbContext context;
        public AuthorController(ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }
        public IActionResult Index()
        {
            return View(context.Author.ToList());
        }
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin, Author")]
        [HttpPost]
        public IActionResult Create(Author author)
        {
            if (ModelState.IsValid)
            {
                context.Add(author);
                context.SaveChanges();
                TempData["Message"] = "Add Author successfully !";
                return RedirectToAction(nameof(Index));
            }
            return View(context.Author.ToList());
        }
        [Authorize(Roles = "Admin, Author")]
        public IActionResult Delete(int id)
        {
            var author = context.Author.Find(id);
            context.Author.Remove(author);
            context.SaveChanges();
            TempData["Message"] = "Delete Author successfully !";
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin, Author")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(context.Author.Find(id));
        }

        [Authorize(Roles = "Admin, Author")]
        [HttpPost]
        public IActionResult Edit(Author author)
        {
            if (ModelState.IsValid)
            {
                context.Update(author);
                context.SaveChanges();
                TempData["Message"] = "Edit author successfully !";
                return RedirectToAction(nameof(Index));
            }
            return View(author);

        }
        [Authorize(Roles = "Admin, Author")]
        public IActionResult Detail(int id)
        {
            var author = context.Author.Include(m => m.Book)
                                     .FirstOrDefault(b => b.Id == id);
            return View(author);
        }
    }
}

Asm1670-Code asm/Controllers/BookController.cs
using Asm1670.Data;
using Asm1670.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace AsmDotNet.Controllers
{
    public class BookController : Controller
    {
        private ApplicationDbContext context;
        public BookController(ApplicationDbContext Dbcontext)
        {
            this.context = Dbcontext;
        }

        [Authorize(Roles = "Store Owner, Admin")]
        public IActionResult ViewBook()
        {

            var books = context.Book.OrderByDescending(m => m.Id).ToList();
            return View(books);
        }

        [Authorize(Roles = "Customer, Storeowner, Admin")]
        //hiển thị giao diện dạng card cho khách hàng order sản phẩm
        public IActionResult Store()
        {
            return View(context.Book.ToList());
        }


        [Authorize(Roles = "Admin, Store Owner")]
        public IActionResult Delete(int id)
        {
            var book = context.Book.Find(id);
            context.Book.Remove(book);
            context.SaveChanges();
            TempData["Message"] = "Delete a book from the store successfully !";
            return RedirectToAction("ViewBook");
        }


        [Authorize(Roles = "Admin, Customer, Store Owner")]
        public IActionResult Detail(int id)
        {
            var book = context.Book.Include(m => m.Category).FirstOrDefault(b => b.Id == id);
            return View(book);
        }

        [Authorize(Roles = "Admin, Store Owner")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categorys = context.Category.ToList();
            return View();
        }
        [Authorize(Roles = "Admin, Store Owner")]
        [HttpPost]
        public IActionResult Create(Book book)
        {
            if (ModelState.IsValid)
            {
                context.Add(book);
                context.SaveChanges();
                TempData["Message"] = "Add a new book successfully !";
                return RedirectToAction(nameof(ViewBook));
            }
            return View(book);
        }

        [Authorize(Roles = "Admin, Store Owner")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categorys = context.Category.ToList();
            return View(context.Book.Find(id));
        }

        [Authorize(Roles = "Admin, Store Owner")]
        [HttpPost]
        public IActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                context.Update(book);
                context.SaveChanges();
                TempData["Message"] = "Edit the chosen book successfully !";
                return RedirectToAction(nameof(ViewBook));
            }
            return View(book);
        }

    }
}

Asm1670-Code asm/Controllers/CartController.cs
using Asm1670.Data;
using Asm1670.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace Asm1670.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext context;
        public CartController(ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }
        public IActionResult ViewCart()
        {
            return View(context.Cart.ToList());
        }
        [Authorize(Roles = "Customer")]
        [HttpPost]
        public IActionResult Make(int id, int quantity)
        {
            var cart = new Cart();
            var book = context.Book.Find(id);
            cart.Book = book;
            cart.BookId = id;
            cart.OrderQuantity = quantity;
            cart.OrderPrice = (int)book.Price * quantity;
            cart.OrderDate = DateTime.Now;
            cart.Email = User.Identity.Name;
            context.Cart.Add(cart);
            book.Quantity -= quantity;
            context.Book.Update(book);
            context.SaveChanges();
            TempData["Success"] = "Order Book Successfully";
            return RedirectToAction("Store","Book");

        }
        [Authorize(Roles = "Store Owner")]
        public IActionResult Delete(int Id)
        {
            var cart = context.Cart.Find(Id);
            context.Cart.Remove(cart);
            context.SaveChanges();
            TempData["Message"] = "Delete a book from the store successfully !";
            return RedirectToAction("ViewCart");
        }
    }
}

Asm1670-Code asm/Controllers/RequestController.cs
using Asm1670.Data;
using Asm1670.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Asm1670.Controllers
{
    public class RequestController : Controller
    {
        private ApplicationDbContext context;
        public RequestController(ApplicationDbContext Dbcontext)
        {
            this.context = Dbcontext;
        }
        [Authorize(Roles = "Admin, Store Owner")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin, Store Owner")]
        [HttpPost]
        public IActionResult Create(Request request)
        {
            if (ModelState.IsValid)
            {
                context.Add(request);
                context.SaveChanges();
                TempData["Message"] = "Add Request successfully !";
                return RedirectToAction(nameof(Index));
            }
            return View(request);
        }
        public IActionResult Index()
        {
            return View(context.Category.ToList());
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Approve(int Id)
        {
            var request = context.Request.Find(Id);
            var category = new Category();
            category.CategoryName = request.RequestName;
            if (ModelState.IsValid)
            {
                context.Add(category);
                context.Request.Remove(request);
                context.SaveChanges();
                TempData["Message"] = "Approve Successfully";
                return RedirectToAction("Index");
            }
            return View(context.Category.ToList());
        }
        [Authorize(Roles = "Admin")]
        public IActionResult ReviewRequest()
        {
            return View(context.Request.ToList());
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Reject(int id)
        {
            var request = context.Request.Find(id);
            context.Request.Remove(request);
            context.SaveChanges();
            TempData["Message"] = "Reject category";
            return RedirectToAction("Index");
        }
    }
}

Asm1670-Code asm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Asm1670</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FPTBook</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="ViewBook">Book Management</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="ReviewRequest">Review Request</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Author</a>
                            </li>
                        </ul>
                    }else if(User.Identity.IsAuthenticated && User.IsInRole("Customer"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Store">Book</a>
                            </li>
                        </ul>

                    }else if (User.Identity.IsAuthenticated && User.IsInRole("Store Owner"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="ViewBook">Book Management</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Create">Make Request</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="ViewCart">View Cart</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Author</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Asm1670 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>