Asm1670-Code asm/Models/Category.cs
using System.Collections.Generic;

namespace Asm1670.Models
{
    public class Category
    {
        public int Id { get; set; }
        
        public string CategoryName { get; set; }

        public ICollection<Book> Book { get; set; }    
    }
}

Asm1670-Code asm/Controllers/BookController.cs
using Asm1670.Data;
using Asm1670.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace AsmDotNet.Controllers
{
    public class BookController : Controller
    {
        private ApplicationDbContext context;
        public BookController(ApplicationDbContext Dbcontext)
        {
            this.context = Dbcontext;
        }

        [Authorize(Roles = "Store Owner, Admin")]
        public IActionResult ViewBook()
        {

            var books = context.Book.OrderByDescending(m => m.Id).ToList();
            return View(books);
        }

        [Authorize(Roles = "Customer, Storeowner, Admin")]
        //hiển thị giao diện dạng card cho khách hàng order sản phẩm
        public IActionResult Store()
        {
            return View(context.Book.ToList());
        }


        [Authorize(Roles = "Admin, Store Owner")]
        public IActionResult Delete(int id)
        {
            var book = context.Book.Find(id);
            context.Book.Remove(book);
            context.SaveChanges();
            TempData["Message"] = "Delete a book from the store successfully !";
            return RedirectToAction("ViewBook");
        }


        [Authorize(Roles = "Admin, Customer, Store Owner")]
        public IActionResult Detail(int id)
        {
            var book = context.Book.Include(m => m.Category).FirstOrDefault(b => b.Id == id);
            return View(book);
        }

        [Authorize(Roles = "Admin, Store Owner")]
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categorys = context.Category.ToList();
            return View();
        }
        [Authorize(Roles = "Admin, Store Owner")]
        [HttpPost]
        public IActionResult Create(Book book)
        {
            if (ModelState.IsValid)
            {
                context.Add(book);
                context.SaveChanges();
                TempData["Message"] = "Add a new book successfully !";
                return RedirectToAction(nameof(ViewBook));
            }
            return View(book);
        }

        [Authorize(Roles = "Admin, Store Owner")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categorys = context.Category.ToList();
            return View(context.Book.Find(id));
        }

        [Authorize(Roles = "Admin, Store Owner")]
        [HttpPost]
        public IActionResult Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                context.Update(book);
                context.SaveChanges();
                TempData["Message"] = "Edit the chosen book successfully !";
                return RedirectToAction(nameof(ViewBook));
            }
            return View(book);
        }

    }
}

Asm1670-Code asm/Controllers/CategoryController.cs
using Asm1670.Data;
using Asm1670.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace Asm1670.Controllers
{
    public class CategoryController : Controller
    {
        private ApplicationDbContext context;
        public CategoryController(ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }

        public IActionResult Index()
        {
            return View(context.Category.ToList());
        }
        [Authorize(Roles = "Admin, Store Owner")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin, Store Owner")]
        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                context.Add(category);
                context.SaveChanges();
                TempData["Message"] = "Add Category successfully !";
                return RedirectToAction(nameof(Index));
            }
            return View(context.Category.ToList());
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var category = context.Category.Find(id);
            context.Category.Remove(category);
            context.SaveChanges();
            TempData["Message"] = "Delete Category successfully !";
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(context.Category.Find(id));
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                context.Update(category);
                context.SaveChanges();
                TempData["Message"] = "Edit Category successfully !";
                return RedirectToAction(nameof(Index));
            }
            return View(category);

        }
        public IActionResult Detail(int id)
        {
            var category = context.Category.Include(m => m.Book)
                                     .FirstOrDefault(b => b.Id == id);
            return View(category);
        }
    }
}

Asm1670-Code asm/Controllers/RequestController.cs
using Asm1670.Data;
using Asm1670.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Asm1670.Controllers
{
    public class RequestController : Controller
    {
        private ApplicationDbContext context;
        public RequestController(ApplicationDbContext Dbcontext)
        {
            this.context = Dbcontext;
        }
        [Authorize(Roles = "Admin, Store Owner")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin, Store Owner")]
        [HttpPost]
        public IActionResult Create(Request request)
        {
            if (ModelState.IsValid)
            {
                context.Add(request);
                context.SaveChanges();
                TempData["Message"] = "Add Request successfully !";
                return RedirectToAction(nameof(Index));
            }
            return View(request);
        }
        public IActionResult Index()
        {
            return View(context.Category.ToList());
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Approve(int Id)
        {
            var request = context.Request.Find(Id);
            var category = new Category();
            category.CategoryName = request.RequestName;
            if (ModelState.IsValid)
            {
                context.Add(category);
                context.Request.Remove(request);
                context.SaveChanges();
                TempData["Message"] = "Approve Successfully";
                return RedirectToAction("Index");
            }
            return View(context.Category.ToList());
        }
        [Authorize(Roles = "Admin")]
        public IActionResult ReviewRequest()
        {
            return View(context.Request.ToList());
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Reject(int id)
        {
            var request = context.Request.Find(id);
            context.Request.Remove(request);
            context.SaveChanges();
            TempData["Message"] = "Reject category";
            return RedirectToAction("Index");
        }
    }
}

Asm1670-Code asm/Views/Category/Create.cshtml
@model Asm1670.Models.Category

<div class="container col-md-6 text-center mt-3">
    <form class="card p-3 bg-light" asp-controller="Request" asp-action="Create" method="post">
        <h3 class="text text-primary">Create Category</h3>
        <div class="form-group">
            <label asp-for="CategoryName" class="text text-success"></label>
            <input asp-for="CategoryName" class="form-control"/>
            <span asp-validation-for="CategoryName" class="text text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Create" />
        </div>
    </form>
</div>

Asm1670-Code asm/Views/Category/Detail.cshtml
@model Asm1670.Models.Category

<div class="container col-md-6 text-center mt-3">
    <table class="table table-bordered">
        <tr>
            <th colspan="2" class="h3 bg-light text-success">@Model.CategoryName</th>
        </tr>
        <tr>
            <th>Book List</th>
            <td>
                @foreach (var book in Model.Book)
                {
                    <a class="font-weight-bold text-italic" asp-controller="Book" asp-action="Detail" asp-route-id="@book.Id">
                        @book.Name
                    </a>
                    <br />
                }
            </td>
        </tr>
    </table>
</div>

Asm1670-Code asm/Views/Category/Edit.cshtml
@model Asm1670.Models.Category

<div class="container col-md-6 text-center mt-3">
    <form class="card p-3 bg-light" asp-controller="Category" asp-action="Edit" method="post">
        <input type="hidden" asp-for="Id" />
        <h3 class="text text-primary">Edit Category</h3>
        <div class="form-group">
            <label asp-for="CategoryName" class="text text-success"></label>
            <input asp-for="CategoryName" class="form-control"/>
            <span asp-validation-for="CategoryName" class="text text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Edit" />
        </div>
    </form>
</div>

Asm1670-Code asm/Views/Category/Index.cshtml
@model ICollection<Category>

<div class="container col-md-6 text-center mt-3">
@if (@TempData["Message"] != null) {
  <p class="alert alert-danger">@TempData["Message"]</p>
}
<table class="table table-bordered">
    <tr>
        <th colspan="3" class="h3 bg-light text-success">Category List</th>
    </tr>
    <tr>
        <th>Category Id</th>
        <th>Category Name</th>
        <th>Action</th>
    </tr>
    @foreach (var category in Model)
    {
        <tr>
            <td>@category.Id</td>
            <td>
                <a class="" asp-controller="Category" asp-action="Detail" asp-route-id="@category.Id">
                    @category.CategoryName
                </a>
            </td>
            <td>
                <a class="" asp-controller="Category" asp-action="Edit" asp-route-id="@category.Id">
                    Edit
                </a>
                <a class="" asp-controller="Category" asp-action="Delete" asp-route-id="@category.Id"
               onclick="    return confirm('Are you sure to delete this Category ?');">
                    Delete
                </a>
            </td>
        </tr>
    }
</table>
</div>